
INSERT INTO public.automation_wiki (tool_name, use_case, category, source_type, source_url, tags, proof_count) VALUES
('n8n', 'סנכרון אנשי קשר בין Gmail ל-Monday באופן אוטומטי', 'CRM', 'Reddit', 'https://reddit.com/r/n8n', ARRAY['gmail','monday','crm','sync'], 89),
('n8n', 'Agent AI שמנתח מיילים ויוצר משימות ב-Jira אוטומטית', 'AI', 'פורום n8n', 'https://community.n8n.io', ARRAY['gmail','jira','ai-agent'], 127),
('n8n', 'חיבור Claude לכוורת לניתוח נתוני לקוחות', 'AI', 'פורום n8n', 'https://community.n8n.io', ARRAY['claude','kaveret','analytics'], 18),
('n8n', 'שימוש ב-Perplexity למחקר לידים אוטומטי', 'מכירות', 'X', 'https://x.com', ARRAY['perplexity','leads','research'], 29),
('n8n', 'העברת דוחות מ-Claude לפריוריטי באופן אוטומטי', 'פיננסי', 'פורום n8n', 'https://community.n8n.io', ARRAY['claude','priority','reports'], 12),
('n8n', 'שליחת התראות Slack כשמשימה ב-Monday מתקרבת לדדליין', 'ניהול פרויקטים', 'Reddit', 'https://reddit.com/r/n8n', ARRAY['slack','monday','notifications'], 67),
('n8n', 'סנכרון מלאי בין Google Sheets ל-Priority', 'תפעול', 'פורום n8n', 'https://community.n8n.io', ARRAY['sheets','priority','inventory'], 34),
('n8n', 'אוטומציה של דוחות שבועיים מ-Google Analytics ל-Slack', 'שיווק', 'Reddit', 'https://reddit.com/r/n8n', ARRAY['analytics','slack','reports'], 73),
('n8n', 'יצירת חשבוניות בכוורת מנתוני Fireberry', 'פיננסי', 'פורום n8n', 'https://community.n8n.io', ARRAY['kaveret','fireberry','invoicing'], 22),
('n8n', 'חיבור ChatGPT לניתוח פידבקים מלקוחות ב-HubSpot', 'AI', 'Reddit', 'https://reddit.com/r/n8n', ARRAY['chatgpt','hubspot','feedback'], 56),
('Make', 'יצירת חשבוניות אוטומטית בפריוריטי מ-Fireberry', 'פיננסי', 'Make Community', 'https://community.make.com', ARRAY['priority','fireberry','invoicing'], 34),
('Make', 'סנכרון מלאי בין Airtable ל-Salesforce', 'מכירות', 'Make Community', 'https://community.make.com', ARRAY['airtable','salesforce','inventory'], 45),
('Make', 'ניתוב לידים אוטומטי מ-HubSpot ל-Monday', 'CRM', 'Make Community', 'https://community.make.com', ARRAY['hubspot','monday','leads'], 61),
('Make', 'סנכרון לקוחות בין Sensei ל-Google Sheets', 'CRM', 'Make Community', 'https://community.make.com', ARRAY['sensei','sheets','crm'], 19),
('Make', 'יצירת דוחות PDF אוטומטיים מנתוני Koala', 'תפעול', 'Make Community', 'https://community.make.com', ARRAY['koala','pdf','reports'], 15),
('Make', 'העברת נתוני מכירות מ-Fireberry ל-Google Sheets', 'מכירות', 'Reddit', 'https://reddit.com/r/integrations', ARRAY['fireberry','sheets','sales'], 38),
('Zapier', 'שליחת תזכורות Slack כשמשימה ב-ClickUp מתקרבת לדדליין', 'ניהול פרויקטים', 'Zapier Community', 'https://community.zapier.com', ARRAY['slack','clickup','notifications'], 56),
('Zapier', 'אוטומציה של דוחות שבועיים מ-Google Analytics ל-Slack', 'שיווק', 'Zapier Community', 'https://community.zapier.com', ARRAY['analytics','slack','reports'], 73),
('Zapier', 'עדכון Notion אוטומטית מ-Gmail', 'ניהול פרויקטים', 'Reddit', 'https://reddit.com/r/zapier', ARRAY['notion','gmail','sync'], 42),
('Zapier', 'יצירת כרטיסים ב-Trello מטפסי Google Forms', 'תפעול', 'Zapier Community', 'https://community.zapier.com', ARRAY['trello','forms','automation'], 31),
('Zapier', 'שליחת SMS ב-WhatsApp Business כשנסגרת עסקה ב-Salesforce', 'מכירות', 'X', 'https://x.com', ARRAY['whatsapp','salesforce','sales'], 27),
('n8n', 'שימוש ב-Gemini לניתוח תמונות מוצרים ויצירת תיאורים', 'AI', 'Reddit', 'https://reddit.com/r/n8n', ARRAY['gemini','ecommerce','ai'], 41),
('n8n', 'חיבור LinkedIn Sales Navigator ל-Fireberry להעשרת לידים', 'מכירות', 'פורום n8n', 'https://community.n8n.io', ARRAY['linkedin','fireberry','leads'], 23),
('Make', 'סנכרון הזמנות מ-Shopify ל-Priority', 'מסחר אלקטרוני', 'Make Community', 'https://community.make.com', ARRAY['shopify','priority','orders'], 52),
('n8n', 'אוטומציה של תהליך גיוס - מ-LinkedIn ל-Monday', 'משאבי אנוש', 'Reddit', 'https://reddit.com/r/n8n', ARRAY['linkedin','monday','hr','recruiting'], 36),
('Zapier', 'שליחת סיכום שבועי מ-Asana ל-Slack עם AI', 'ניהול פרויקטים', 'Zapier Community', 'https://community.zapier.com', ARRAY['asana','slack','ai','summary'], 48),
('n8n', 'חיבור Perplexity למחקר מתחרים אוטומטי ושמירה ב-Notion', 'שיווק', 'X', 'https://x.com', ARRAY['perplexity','notion','research'], 33),
('Make', 'אוטומציה של הפקת דוחות כספיים מ-Priority ל-Google Sheets', 'פיננסי', 'Make Community', 'https://community.make.com', ARRAY['priority','sheets','finance'], 29),
('n8n', 'Webhook chain - קבלת אירוע מ-Stripe ועדכון CRM + חשבונית', 'תפעול', 'פורום n8n', 'https://community.n8n.io', ARRAY['stripe','crm','webhook','invoicing'], 85),
('Zapier', 'העברת לידים מ-Facebook Ads ל-HubSpot אוטומטית', 'שיווק', 'Reddit', 'https://reddit.com/r/zapier', ARRAY['facebook','hubspot','leads','ads'], 94);
